# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/AFD-Illinois/kharma.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@gitlab.com:AFD-Illinois/kharma.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
