name: Regression tests (CPU)

on:
  # Oh push to stable/dev incl. automated merge after branch tests
  push:
    branches: [ stable, dev ]
  # On every push of pull requests to stable/dev. Frequent!
  pull_request:
    branches: [ stable, dev ]
  # when triggered manually
  workflow_dispatch:

env:
  NPROC: 4
  MPI_NUM_PROCS: 4
  OMP_NUM_THREADS: 1
  HOST_ARCH: "HSW"
  MPI_EXTRA_ARGS: "--oversubscribe"

jobs:
  # Job 1: Compilation
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Install prereqs
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install libopenmpi-dev libhdf5-openmpi-dev libfftw3-dev
          sudo apt-get install hdf5-tools cmake
      - name: Run compilation
        run: bash -i ./make.sh clean noopenmp
      - uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: |
            kharma.host
            make_args
          if-no-files-found: 'error'

  # Job 2: Test Matrix
  test:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        # add back 'resize' when new solvers work
        test_name:
        - all_pars
        - anisotropic_conduction
        - bondi
        - bondi_viscous
        - bz_monopole
        - conducting_atmosphere
        - emhdmodes
        - emhdshock
        - hubble_flow
        - mhdmodes
        - mhdmodes_smr
        - noh
        - regrid
        - reinit
        - restart
        - tilt_init
        - torus_sanity
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - uses: actions/download-artifact@v8
        with:
          name: build-artifacts
      - name: Install prereqs
        run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev libhdf5-openmpi-dev libfftw3-dev
          sudo apt-get install hdf5-tools
          pip install git+https://github.com/c-prather/pyharm@dev
      - name: Run ${{ matrix.test_name }}
        working-directory: tests/${{ matrix.test_name }}
        run: bash -i ./run.sh
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: ${{ matrix.test_name }}-artifacts
          path: |
            tests/${{ matrix.test_name }}
            !*.phdf
            !*.rhdf
            !*.xdmf
            !*.h5
